from sqlalchemy import Column, String, Boolean
from app.database.base import Base

class AdminProfile(Base):
    __tablename__ = "admin_profiles"

    # This ID will match the unique user ID generated by Supabase
    id = Column(String, primary_key=True, index=True)
    email = Column(String, unique=True, index=True)
    full_name = Column(String)
    is_approved = Column(Boolean, default=False)